#!/bin/sh
if [ ! -f /usr/lib/enigma2/python/Components/Task.py.org ]; then
	if [ -f /usr/lib/enigma2/python/Components/Task.py ]; then
		cp /usr/lib/enigma2/python/Components/Task.py /usr/lib/enigma2/python/Components/Task.py.org
	fi
	if [ -f /usr/lib/enigma2/python/Components/Task.pyc ]; then
		cp /usr/lib/enigma2/python/Components/Task.pyc /usr/lib/enigma2/python/Components/Task.pyc.org
	fi
fi
cp  /usr/lib/enigma2/python/Plugins/SystemPlugins/JobCockpit/Components/Task.py /usr/lib/enigma2/python/Components/Task.py

echo "***********************************"
echo "*           JobCockpit            *"
echo "*               by                *"
echo "*          xcentaurix             *"
echo "***********************************"
echo ""
echo "Plugin installed successfully."
echo "Please restart Enigma2 now!"
echo ""
exit 0
